// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWjkfp9L0FBSwAJUJ3kpJBntxUvCFxIPw',
    appId: '1:594160992162:web:7273ffe8cb0a37093fbcfb',
    messagingSenderId: '594160992162',
    projectId: 'chat-app-19ce0',
    authDomain: 'chat-app-19ce0.firebaseapp.com',
    storageBucket: 'chat-app-19ce0.firebasestorage.app',
    measurementId: 'G-SJ5JQ9R3K5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL9L6M_jbEL-QInEXyQp0E99W4ybe2L-U',
    appId: '1:594160992162:android:7da83880f428b5d63fbcfb',
    messagingSenderId: '594160992162',
    projectId: 'chat-app-19ce0',
    storageBucket: 'chat-app-19ce0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgaO2PwpQmWG-ahJepHGY9ACzN-uQffc4',
    appId: '1:594160992162:ios:45e98446a9e9e7193fbcfb',
    messagingSenderId: '594160992162',
    projectId: 'chat-app-19ce0',
    storageBucket: 'chat-app-19ce0.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgaO2PwpQmWG-ahJepHGY9ACzN-uQffc4',
    appId: '1:594160992162:ios:45e98446a9e9e7193fbcfb',
    messagingSenderId: '594160992162',
    projectId: 'chat-app-19ce0',
    storageBucket: 'chat-app-19ce0.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWjkfp9L0FBSwAJUJ3kpJBntxUvCFxIPw',
    appId: '1:594160992162:web:80857460e90f782c3fbcfb',
    messagingSenderId: '594160992162',
    projectId: 'chat-app-19ce0',
    authDomain: 'chat-app-19ce0.firebaseapp.com',
    storageBucket: 'chat-app-19ce0.firebasestorage.app',
    measurementId: 'G-C1E6XLCQYF',
  );
}
